### ISSUE TITLE
add introductory paragraph or website

### ISSUE THREAD

**Issue by andyczerwonka** [oracle/wookiee#105]
Read the README, don’t get it. It talks about what it’s comprised of, not what it’s for. Maybe add a introductory paragraph or a page around the target use case.

**Comment by malibuworkcrew** [comment]
Thanks for keeping us honest, have begun filling out our Docs more-- with example Services to come as well. Starting with this entry here: https://github.com/oracle/wookiee#usage

**Comment by pcross616** [comment]
Just added examples and more documentation via PR #114

**Comment by malibuworkcrew** [comment]
Have done a few changes the last couple months to address this:
New intro paragraph in main repo: 
https://github.com/oracle/wookiee#usage

A simple as possible example with instructions on running: 
https://github.com/oracle/wookiee/tree/master/examples/basic-service

An example wookiee-akka-http service with instructions: 
https://github.com/oracle/wookiee-akka-http/tree/master/examples/akka-http-service

Significant cleanup of dependencies, config watching documentation, and TestHarness improvements:
https://github.com/oracle/wookiee/releases/tag/1.3.11

Maven instructions for adding dependencies to most components:
https://github.com/oracle/wookiee-zookeeper#adding-to-pom

Creation of a MockZookeeper to allow for unit testing of services/components that use ZK:
https://github.com/oracle/wookiee-zookeeper#testing-zookeeper-mock
https://github.com/oracle/wookiee-zookeeper/releases/tag/1.3.10

Also look forward to a possible article on Wookiee forthcoming...
