### ISSUE TITLE
Swap from Specs2/JUnit to ScalaTest

### ISSUE THREAD

**Issue by AlexanderNull** [oracle/wookiee#142]
This project's out of step now with our main unit test framework. Looks like Specs2+JUnit doesn't support things like for comprehension driven test definitions or even throwing multiple asserts into a single test. This makes writing tests that can catch multiple permutations of inputs exceedingly difficult.
Example of a working ScalaTest for comprehension:
`"upperCase function" should {
        for ((inputString, expectedResult) <- Seq(
          ("a", "A"),
          ("bcd", "BCD"),
          ("jhk1", "JHK1")
        )) s"upperCase string $inputString" in {
          assert(upperCase(inputString) == expectedResult)
        }
    } `

Can't do this with Specs2/JUnit though, so instead you would need to write out 3 individual tests to get the same result. This simple example might not be difficult to do but with the ScalaTest capabilities I can easily add another 20 test cases to the same test and have meaningful results output for each individual iteration.

**Comment by malibuworkcrew** [comment]
We still have a few specs2 tests left in wookiee-core/test, I converted everything in Wookiee ZK but we should make sure we convert everything else as we go. I'll throw a task onto our stories

**Comment by malibuworkcrew** [comment]
Here's the PR that does this:
https://github.com/oracle/wookiee/pull/154
