### ISSUE TITLE
Idea for filters

### ISSUE THREAD

**Issue by oneam** [oracle/wookiee#64]
Twitter has an interesting post about how they use Scala:
http://monkey.org/~marius/scala2015.pdf

Have you thought of adding something similar to the Filter class to Wookie?
It could have a single method:

<pre>def filter[T](bean:Option[CommandBean], command:Command[T]) : Future[CommandResponse[T]]</pre>

It could be used for logging, metrics, authentication... All the usual stuff that goes in a tradition framework filter chain.

**Comment by Crashfreak** [comment]
What Filter class are you referring to exactly? Unless I am completely missing what you are saying, we don't have any Filter class in Wookiee. At least not one that is named "Filter", are you referencing another class differently named?

**Comment by oneam** [comment]
There is no Filter class in Wookiee. There is logging. There will probably be authentication, metrics, throttling, isolation (bulk-heading and short-circuiting) and other non-functional features.

An engineer at Twitter presented an interesting functional interface for services that looks remarkably like Commands in Wookiee. They also presented a Filter interface that provides a way to add the pieces described above to the Services. That interface makes a lot of sense and it would be cool if Wookiee implemented something similar.

What do you think of the Filter interface? Would Wookiee benefit from something like that?

**Comment by Crashfreak** [comment]
Ah, sorry my misunderstanding. That looks like a really interesting idea actually. We are looking at improving some of the things you mentioned and seems like it could definitely benefit from something like that.

**Comment by asarkar** [comment]
Ding, after 3 years 😄 Is this feature still under consideration?

**Comment by malibuworkcrew** [comment]
We've ended up building a lot of custom implementations of Wookiee Services that basically have this same function, where we've setup a class (e.g. trait ParentOfReadCommands extends Command) that is extended by a group of commands and runs some common functionality (i.e. filters) before dropping into the individual commands. We could have used something like this that routes through a totally separate class/actor first then forwards on the the destination command. So yes I could still see this feature being done and know it would be beneficial, but we have not put it on the short term road map still.

**Comment by malibuworkcrew** [comment]
Going to close this, our new Wookiee v2 functional model seems to add functionality very similar to this. Or at least it enables users who want to have their business logic include filters. Please speak up if this doesn't seem to cover it
